Add ya2d and dbglogger
bucanero/ps3libraries pull request #2
Opened 2021-10-02 20:11 UTC by rhynec

2021-10-10 05:11 UTC, rhynec commented
Added bzip2 and mini18n to library scripts. The new mini18n script is added to allow for PKGi compilation straight from setup. I also created a branch which only provides the libraries missing from the 2020/07/17 pre-built toolchain: https://github.com/rhynec/ps3libraries/tree/extra-install

2022-12-28 10:23 UTC, bucanero commented
I totally missed this PR. I'll review it

2022-12-28 10:32 UTC, bucanero requested changes
Needs new link for `dbglogger`

2022-12-28 10:32 UTC, bucanero commented on scripts/035-bzip2_dbglogger.sh
> +wget --no-check-certificate https://github.com/bucanero/psl1ght-libs/tarball/master -O psl1ght-libs.tar.gz
Now there's a new repo for the `dbglogger` library.

Can you update the script so it downloads from https://github.com/bucanero/dbglogger ?

2023-01-12 01:52 UTC, rhynec commented
Hey @bucanero!

I deleted my fork a while back, so it was easier for me to re-fork and merge the changes manually. I'll open a separate PR.

2023-01-12 01:52 UTC, closed without merging